name: Translate CLI CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  cli-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp
      - name: CLI help
        run: |
          python -m translate --help || true

